name: Deploy Backend Staging AWS

on:
  push:
    branches:
      - staging
    paths:
      - 'backend/**'
      - '.github/workflows/aws_backend.yml'
      - 'infra/**'


jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    name: DEPLOY AWS AND BACKEND
    environment: staging
    env:
      env_deploy: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_STAGING }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR backend
        id: build-image-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND_STAGING }}
          IMAGE_TAG: ${{ github.sha }}
          ENV: staging
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f infra/Docker/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform update
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_STAGING }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_STAGING }}
          PASS_DB: ${{ secrets.PASSWORD_DATABASE_STAGING }}
          NAME_DB: ${{ secrets.NAME_DATABASE_STAGING }}
          USER_DB: ${{ secrets.USER_NAME_DATABASE_STAGING }}
          TERRAFORM_STATE_BUCKET_NAME: ${{ secrets.TERRAFORM_STATE_BUCKET_NAME_STAGING }}
          IMAGE_BE: ${{ steps.build-image-backend.outputs.image }}
        run: |
          cd infra/
          bash update_vars.sh
          terraform init -backend-config=./cfbackend.tfvars
          terraform plan -var="stage_name=stg"
          terraform apply -var="stage_name=stg" -auto-approve
